require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DivisionsController do

  # This should return the minimal set of attributes required to create a valid
  # Division. As you add validations to Division, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "divname" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DivisionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  let(:div1) {FactoryGirl.create(:division)}

  describe "GET index" do
    it "assigns all divisions as @divisions" do
      #division = Division.create! valid_attributes
      get :index
      assigns(:divisions).should eq([div1])
    end
  end

  describe "GET show" do
    it "assigns the requested division as @division" do
      #division = Division.create! valid_attributes
      get :show, id: div1
      assigns(:division).should eq(div1)
    end
  end

  describe "GET new" do
    it "assigns a new division as @division" do
      get :new
      assigns(:division).should be_a_new(Division)
    end
  end

  describe "GET edit" do
    it "assigns the requested division as @division" do
      #division = Division.create! valid_attributes
      get :edit, id: div1
      assigns(:division).should eq(div1)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Division" do
        expect {
          post :create, division: FactoryGirl.attributes_for(:division)
        }.to change(Division, :count).by(1)
      end

      it "assigns a newly created division as @division" do
        post :create, division: FactoryGirl.attributes_for(:division)
        assigns(:division).should be_a(Division)
        assigns(:division).should be_persisted
      end

      it "redirects to the created division" do
        post :create, division: FactoryGirl.attributes_for(:division)
        response.should redirect_to(Division.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved division as @division" do
        # Trigger the behavior that occurs when invalid params are submitted
        Division.any_instance.stub(:save).and_return(false)
        post :create, {:division => { "divname" => "invalid value" }}, valid_session
        assigns(:division).should be_a_new(Division)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Division.any_instance.stub(:save).and_return(false)
        post :create, {:division => { "divname" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      before :each do
        @div2 = FactoryGirl.create(:division)
      end
      it "updates the requested division" do
        #division = Division.create! valid_attributes
        # Assuming there are no other divisions in the database, this
        # specifies that the Division created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        put :update, id: @div2, division: FactoryGirl.attributes_for(:division, divname: "Second Div")
        @div2.reload
        @div2.divname.should eq("Second Div")
      end

      it "assigns the requested division as @division" do
        #division = Division.create! valid_attributes
        put :update, id: @div2, division: FactoryGirl.attributes_for(:division)
        assigns(:division).should eq(@div2)
      end

      it "redirects to the division" do
        #division = Division.create! valid_attributes
        put :update, id: @div2, division: FactoryGirl.attributes_for(:division)
        response.should redirect_to(@div2)
      end
    end

    describe "with invalid params" do
      before :each do
        @div = FactoryGirl.create(:division)
      end
      it "assigns the division as @division" do
        #division = Division.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        put :update, id: @div, division: FactoryGirl.attributes_for(:division)
        assigns(:division).should eq(@div)
   end

      it "re-renders the 'edit' template" do
        #division = Division.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        #Division.any_instance.stub(:save).and_return(false)
        put :update, id: @div, division: FactoryGirl.attributes_for(:invalid_division)
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested division" do
      #division = Division.create! valid_attributes
      expect {
        delete :destroy, id: div1
      }.to change(Division, :count).by(-1)
    end

    it "redirects to the divisions list" do
      #division = Division.create! valid_attributes
      delete :destroy, id: div1
      response.should redirect_to(divisions_url)
    end
  end

end
